'judul' => $request->,
'kategori_id' => $request->,
'slug' => $request->,
'poster' => $request->,
'video' => $request->,
'sutradara' => $request->,
'bintangFilm' => $request->,
'genre' => 
'rating' => $request->,
'durasi' => $request->,
'sinopsis' => $request->